---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Create lighthouse directory
  become: true
  ansible.builtin.file:
    path: "{{ lighthouse_dir }}"
    state: directory
    mode: '0755'

- name: Clone Lighthouse repository
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    dest: "{{ lighthouse_dir }}"
    version: master

- name: Configure nginx for Lighthouse
  become: true
  ansible.builtin.template:
    src: lighthouse-nginx.conf.j2
    dest: /etc/nginx/sites-available/lighthouse
    mode: '0644'
  notify: Reload nginx

- name: Enable Lighthouse site
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/lighthouse
    dest: /etc/nginx/sites-enabled/lighthouse
    state: link
  notify: Reload nginx

- name: Remove default nginx
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Start nginx service
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
